### ISSUE TITLE
Change NodeType results in error

### ISSUE THREAD

**Issue by simonedelmann** [Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor#300] opened 2019-05-08 16:32 UTC
I just installed this package and set up ElasticSearch for a simple site package, I'm just creating.

The bug: Changing a node's type immediately results in an error.
This appears for changing document aswell as content nodes.

> 
> Elasticsearch request failed. 
> [GET http://search:9200//_search/scroll?scroll=1m]: Array ( [root_cause] => Array ( [0] => Array ( [type] => illegal_argument_exception [reason] => request [//_search/scroll] contains unrecognized parameter: [scroll] ) ) [type] => illegal_argument_exception [reason] => request [//_search/scroll] contains unrecognized parameter: [scroll] ) ; Response body: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [//_search/scroll] contains unrecognized parameter: [scroll]"}],"type":"illegal_argument_exception","reason":"request [//_search/scroll] contains unrecognized parameter: [scroll]"},"status":400} Request data: DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAA6AFkxiQjJSS2gxVDZlbUIyUV9YWklPeEEAAAAAAAAOghZMYkIyUktoMVQ2ZW1CMlFfWFpJT3hBAAAAAAAADn8WTGJCMlJLaDFUNmVtQjJRX1haSU94QQAAAAAAAA6BFkxiQjJSS2gxVDZlbUIyUV9YWklPeEEAAAAAAAAOgxZMYkIyUktoMVQ2ZW1CMlFfWFpJT3hB
> 

Edit: I'm using the latest versions of all related packages:
Neos/Neos: 4.3.0
Flowpack/ElasticSearch: 2.0.4
Flowpack/ElasticSearch.ContentRepositoryAdapter: 5.0.1
ElasticSearch is running in a docker container using the official Elasticsearch image, version 5.

**Comment by bweinzierl** [comment] 2019-06-17 16:29
Had the same issue when switching document nodetypes. This PR fixes the error but it is not tested if the intended behaviour works again. But it should :)
It would be great if someone with a bit more insight into this package could check.
Maybe @daniellienert ?

**Comment by DrillSergeant** [comment] 2019-10-18 08:32
Just encountered the same issue

**Comment by bweinzierl** [comment] 2019-10-18 09:37
@DrillSergeant check out my PR :)

**Comment by DrillSergeant** [comment] 2019-10-18 11:34
Unfortunately we are bound to the fork https://github.com/dfeyer/Flowpack.ElasticSearch.ContentRepositoryAdaptor/tree/feature-oneindex-per-dimensionspreset which is not merged. I wanted to help funding the merge but the customer did not agree to sponsor it, so we are decoupled from the official package for now. :-(

But if I find time, I will check your PR code and try to add it somehow in the fork.

**Closed** 2020-03-28 10:39 UTC
